apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web-harish
  description: The place to be, for great artists
  archerID: 34575
  labels:
    system: public-websites
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
spec:
  type: website
  lifecycle: production
  owner: artist-relations@example.com
  
